if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js?v=3').catch(()=>{});
const db=supabase.createClient('https://etchkccnckeuzsifvgld.supabase.co','sb_publishable_XXJU11HBVpyROr4150rgwg_gEGQjlf1'),$=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);let me,team,items=[],mode='all',signup=false,editId=null;
const T={walk:['Marche rapide','🚶'],pushup:['Pompes','💪'],abs:['Abdos','⚡'],dumbbell_left:['Haltère · bras gauche','🏋️'],dumbbell_right:['Haltère · bras droit','🏋️'],other:['Autre exercice','✨']};
$('#toggle').onclick=()=>{signup=!signup;$('#authTitle').textContent=signup?'Créer mon compte':'Se connecter';$('#nameBox').hidden=!signup;$('#submit').textContent=signup?'Créer mon compte':'Se connecter';$('#toggle').textContent=signup?'Déjà inscrit ? Se connecter':'Pas encore de compte ? S’inscrire'};
$('#login').onsubmit=async e=>{e.preventDefault();let r=signup?await db.auth.signUp({email:$('#email').value,password:$('#password').value,options:{data:{display_name:$('#name').value||$('#email').value.split('@')[0]}}}):await db.auth.signInWithPassword({email:$('#email').value,password:$('#password').value});$('#authError').textContent=r.error?r.error.message:(signup?'Compte créé. Confirme ton e-mail si demandé.':'')};
$('#logout').onclick=()=>db.auth.signOut();async function boot(s){$('#auth').hidden=!!s;$('#app').hidden=!s;if(!s)return;let {data,error}=await db.from('profiles').select('*').eq('id',s.user.id).single();if(error){$('#app').innerHTML='<p style="padding:30px">La base doit être initialisée.</p>';return}me=data;$('#who').textContent=me.display_name;loadTeam()}
async function loadTeam(){let {data}=await db.from('group_members').select('group_id,groups(*)').eq('user_id',me.id).maybeSingle();$('#setup').hidden=!!data;$('#dash').hidden=!data;if(!data)return;team=data.groups;$('#code').textContent=team.invite_code;$('#hello').textContent=team.name+', on continue.';load()}
$('#create').onclick=async()=>{let {error}=await db.rpc('create_group',{group_name:$('#groupName').value});$('#groupError').textContent=error?.message||'';if(!error)loadTeam()};$('#join').onclick=async()=>{let {error}=await db.rpc('join_group',{join_code:$('#codeIn').value.toUpperCase()});$('#groupError').textContent=error?.message||'';if(!error)loadTeam()};$('#copy').onclick=()=>navigator.clipboard.writeText(team.invite_code);
async function load(){let {data}=await db.from('activities').select('*,profiles(display_name)').eq('group_id',team.id).order('performed_at',{ascending:false});items=data||[];render()}
function info(a){let d=a.details||{};return a.type==='walk'?d.distance+' km · '+d.duration+' min':d.sets+' séries × '+d.reps+' répétitions'+(d.weight?' · '+d.weight+' kg':'')}function safe(s){let d=document.createElement('div');d.textContent=s;return d.innerHTML}
function render(){let x=items.filter(a=>mode==='all'||(mode==='mine')===(a.user_id===me.id));$('#list').innerHTML=x.length?x.map(a=>'<div class="entry"><div class="icon">'+T[a.type][1]+'</div><div><h3>'+T[a.type][0]+' · '+a.profiles.display_name+'</h3><p>'+info(a)+(a.note?' · '+safe(a.note):'')+'</p></div><div class="entryEnd"><time>'+new Date(a.performed_at+'T12:00').toLocaleDateString('fr-FR',{day:'numeric',month:'short'})+'</time>'+(a.user_id===me.id?'<button class="edit" data-edit="'+a.id+'">Modifier</button>':'')+'</div></div>').join(''):'<p class="empty">Aucune activité pour le moment.</p>';let monday=new Date();monday.setHours(0,0,0,0);monday.setDate(monday.getDate()-monday.getDay()+1);$('#week').textContent=items.filter(a=>new Date(a.performed_at+'T12:00')>=monday).length;let ds=[];for(let i=6;i>=0;i--){let d=new Date();d.setDate(d.getDate()-i);let z=d.toISOString().slice(0,10);ds.push([d,items.filter(a=>a.performed_at===z).length])}let m=Math.max(1,...ds.map(d=>d[1]));$('#chart').innerHTML=ds.map(d=>'<div class="day"><div class="bar" style="height:'+Math.max(4,d[1]/m*120)+'px"></div><span>'+d[0].toLocaleDateString('fr-FR',{weekday:'short'}).slice(0,2)+'</span></div>').join('')}
$$('.filters button').forEach(b=>b.onclick=()=>{$$('.filters button').forEach(x=>x.classList.remove('on'));b.classList.add('on');mode=b.dataset.f;render()});
function fields(){let t=$('#type').value;$('#fields').innerHTML=t==='walk'?'<div class="row"><label>Distance (km)<input id="distance" type="number" step=".1" value="4" required></label><label>Durée (min)<input id="duration" type="number" value="45" required></label></div>':'<div class="row"><label>Séries<input id="sets" type="number" value="3" required></label><label>Répétitions<input id="reps" type="number" value="10" required></label></div>'+(t.startsWith('dumbbell')?'<label>Poids (kg)<input id="weight" type="number" step=".5" value="5" required></label>':'')}
function openNew(){editId=null;$('#activity').reset();$('#modalHeading').textContent='Ajouter une activité';$('#deleteActivity').hidden=true;$('#saveActivity').textContent='Enregistrer';$('#date').value=new Date().toISOString().slice(0,10);fields();$('#modal').showModal()}
function openEdit(id){let a=items.find(x=>x.id===id);if(!a||a.user_id!==me.id)return;editId=id;$('#modalHeading').textContent='Modifier l’activité';$('#deleteActivity').hidden=false;$('#saveActivity').textContent='Enregistrer les modifications';$('#type').value=a.type;$('#note').value=a.note||'';$('#date').value=a.performed_at;fields();if(a.type==='walk'){$('#distance').value=a.details.distance;$('#duration').value=a.details.duration}else{$('#sets').value=a.details.sets;$('#reps').value=a.details.reps;if($('#weight'))$('#weight').value=a.details.weight||0}$('#modal').showModal()}
$('#type').onchange=fields;$('#add').onclick=openNew;$('#close').onclick=()=>$('#modal').close();$('#list').onclick=e=>{let b=e.target.closest('[data-edit]');if(b)openEdit(b.dataset.edit)};
$('#deleteActivity').onclick=async()=>{if(!editId||!confirm('Supprimer définitivement cette activité ?'))return;let {error}=await db.from('activities').delete().eq('id',editId).eq('user_id',me.id);$('#activityError').textContent=error?.message||'';if(!error){$('#modal').close();editId=null;load()}};
$('#activity').onsubmit=async e=>{e.preventDefault();let t=$('#type').value,d=t==='walk'?{distance:+$('#distance').value,duration:+$('#duration').value}:{sets:+$('#sets').value,reps:+$('#reps').value,weight:$('#weight')?+$('#weight').value:null},payload={type:t,details:d,note:$('#note').value,performed_at:$('#date').value};let r=editId?await db.from('activities').update(payload).eq('id',editId).eq('user_id',me.id):await db.from('activities').insert({...payload,group_id:team.id,user_id:me.id});$('#activityError').textContent=r.error?.message||'';if(!r.error){$('#modal').close();editId=null;e.target.reset();load()}};
db.auth.onAuthStateChange((_e,s)=>setTimeout(()=>boot(s),0));db.auth.getSession().then(x=>boot(x.data.session));

