const db=supabase.createClient('https://etchkccnckeuzsifvgld.supabase.co','sb_publishable_XXJU11HBVpyROr4150rgwg_gEGQjlf1'),$=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);
let me,team,items=[],mode='all',signup=false,editId=null,statType='walk';
const T={walk:['Marche rapide','🚶'],pushup:['Pompes','💪'],abs:['Abdos','⚡'],dumbbell_left:['Haltère · bras gauche','🏋️'],dumbbell_right:['Haltère · bras droit','🏋️'],other:['Autre exercice','✨']};
$('#toggle').onclick=()=>{signup=!signup;$('#authTitle').textContent=signup?'Créer mon compte':'Se connecter';$('#nameBox').hidden=!signup;$('#submit').textContent=signup?'Créer mon compte':'Se connecter';$('#toggle').textContent=signup?'Déjà inscrit ? Se connecter':'Pas encore de compte ? S’inscrire'};
$('#login').onsubmit=async e=>{e.preventDefault();let r=signup?await db.auth.signUp({email:$('#email').value,password:$('#password').value,options:{data:{display_name:$('#name').value||$('#email').value.split('@')[0]}}}):await db.auth.signInWithPassword({email:$('#email').value,password:$('#password').value});$('#authError').textContent=r.error?r.error.message:(signup?'Compte créé. Confirme ton e-mail si demandé.':'')};
$('#logout').onclick=()=>db.auth.signOut();
async function boot(s){$('#auth').hidden=!!s;$('#app').hidden=!s;if(!s)return;let {data,error}=await db.from('profiles').select('*').eq('id',s.user.id).single();if(error){$('#app').innerHTML='<p style="padding:30px">La base doit être initialisée.</p>';return}me=data;$('#who').textContent=me.display_name;loadTeam()}
async function loadTeam(){let {data}=await db.from('group_members').select('group_id,groups(*)').eq('user_id',me.id).maybeSingle();$('#setup').hidden=!!data;$('#dash').hidden=!data;if(!data)return;team=data.groups;$('#code').textContent=team.invite_code;$('#hello').textContent=team.name+', on continue.';load()}
$('#create').onclick=async()=>{let {error}=await db.rpc('create_group',{group_name:$('#groupName').value});$('#groupError').textContent=error?.message||'';if(!error)loadTeam()};$('#join').onclick=async()=>{let {error}=await db.rpc('join_group',{join_code:$('#codeIn').value.toUpperCase()});$('#groupError').textContent=error?.message||'';if(!error)loadTeam()};$('#copy').onclick=()=>navigator.clipboard.writeText(team.invite_code);
async function load(){let {data}=await db.from('activities').select('*,profiles(display_name)').eq('group_id',team.id).order('performed_at',{ascending:false});items=data||[];render()}
function volume(a){let d=a.details||{};return a.type==='walk'?+(d.distance||0):+(d.sets||0)*+(d.reps||0)}function xpFor(a){return a.type==='walk'?Math.round(volume(a)*10):Math.round(volume(a)/2)}function safe(s){let d=document.createElement('div');d.textContent=s;return d.innerHTML}
function info(a){let d=a.details||{};if(a.type==='walk')return d.distance+' km · '+d.duration+' min'+(d.effort?' · '+d.effort:'');return d.sets+' séries × '+d.reps+' répétitions'+(d.weight?' · '+d.weight+' kg':'')+(d.rest?' · repos '+d.rest+' s':'')}
function render(){let x=items.filter(a=>mode==='all'||(mode==='mine')===(a.user_id===me.id));$('#list').innerHTML=x.length?x.map(a=>'<div class="entry"><div class="icon">'+T[a.type][1]+'</div><div><h3>'+T[a.type][0]+' · '+a.profiles.display_name+'</h3><p>'+info(a)+(a.note?' · '+safe(a.note):'')+'</p></div><div class="entryEnd"><time>'+new Date(a.performed_at+'T12:00').toLocaleDateString('fr-FR',{day:'numeric',month:'short'})+'</time>'+(a.user_id===me.id?'<button class="edit" data-edit="'+a.id+'">Modifier</button>':'')+'</div></div>').join(''):'<p class="empty">Aucune activité pour le moment.</p>';let monday=new Date();monday.setHours(0,0,0,0);monday.setDate(monday.getDate()-monday.getDay()+1);$('#week').textContent=items.filter(a=>new Date(a.performed_at+'T12:00')>=monday).length;$('#xp').textContent=items.filter(a=>a.user_id===me.id).reduce((n,a)=>n+xpFor(a),0);renderStats()}
$$('.filters button').forEach(b=>b.onclick=()=>{$$('.filters button').forEach(x=>x.classList.remove('on'));b.classList.add('on');mode=b.dataset.f;render()});
function ownForStat(a){return a.user_id===me.id&&(statType==='dumbbell'?a.type.startsWith('dumbbell'):a.type===statType)}function allForStat(a){return statType==='dumbbell'?a.type.startsWith('dumbbell'):a.type===statType}
function renderStats(){let relevant=items.filter(allForStat),mine=relevant.filter(a=>a.user_id===me.id),partner=relevant.filter(a=>a.user_id!==me.id),days=[];for(let i=6;i>=0;i--){let d=new Date();d.setDate(d.getDate()-i);let iso=d.toISOString().slice(0,10);days.push({d,n:mine.filter(a=>a.performed_at===iso).reduce((s,a)=>s+volume(a),0)})}let max=Math.max(1,...days.map(x=>x.n)),mineTotal=mine.reduce((s,a)=>s+volume(a),0),partnerTotal=partner.reduce((s,a)=>s+volume(a),0),record=Math.max(0,...mine.map(volume)),unit=statType==='walk'?'KM':'RÉP.';$('#statsPanel').innerHTML='<div class="stat-cards"><div><small>MON TOTAL</small><b>'+format(mineTotal)+'</b><span>'+unit+'</span></div><div><small>MON RECORD</small><b>'+format(record)+'</b><span>'+unit+'</span></div></div><div class="chart-title">'+(statType==='walk'?'DISTANCE PAR JOUR':'RÉPÉTITIONS PAR JOUR')+'</div><div class="game-chart">'+days.map(x=>'<div class="game-day"><strong>'+format(x.n)+'</strong><i style="height:'+Math.max(4,x.n/max*120)+'px"></i><span>'+x.d.toLocaleDateString('fr-FR',{weekday:'short'}).slice(0,3)+'</span></div>').join('')+'</div><div class="compare"><small>COMPARAISON · TOTAL</small>'+compareRow('MOI',mineTotal,Math.max(mineTotal,partnerTotal,1),'cyan')+compareRow('PARTENAIRE',partnerTotal,Math.max(mineTotal,partnerTotal,1),'purple')+'</div>'}
function format(n){return Number.isInteger(n)?n:n.toFixed(1)}function compareRow(name,val,max,cls){return '<div class="compare-row"><b>'+name+'</b><i><span class="'+cls+'" style="width:'+val/max*100+'%"></span></i><strong>'+format(val)+'</strong></div>'}
$('#statTabs').onclick=e=>{let b=e.target.closest('[data-stat]');if(!b)return;$$('#statTabs button').forEach(x=>x.classList.remove('on'));b.classList.add('on');statType=b.dataset.stat;renderStats()};
function stepper(id,label,value,min=0,step=1,suffix=''){return '<div class="step-block"><small>'+label+'</small><div class="stepper"><button type="button" data-step="'+id+'" data-delta="-'+step+'">−</button><b id="'+id+'" data-min="'+min+'">'+value+'</b><span>'+suffix+'</span><button type="button" data-step="'+id+'" data-delta="'+step+'">＋</button></div></div>'}
function buildFields(type,d={}){if(type==='walk'){$('#fields').innerHTML='<div class="quick-block"><small>DISTANCE</small><div class="presets"><button type="button" data-distance="2">2 KM</button><button type="button" data-distance="4" class="on">4 KM</button><button type="button" data-distance="5">5 KM</button><button type="button" data-distance="0">LIBRE</button></div><label id="customDistance" hidden>Distance personnalisée (km)<input id="distanceInput" type="number" min=".1" step=".1" value="4"></label></div>'+stepper('duration','DURÉE',d.duration||45,1,5,'MIN')+'<div class="quick-block"><small>EFFORT</small><div class="presets effort"><button type="button" data-effort="Facile">FACILE</button><button type="button" data-effort="Soutenu" class="on">SOUTENU</button><button type="button" data-effort="Intense">INTENSE</button></div></div>';$('#fields').dataset.distance=d.distance||4;$('#fields').dataset.effort=d.effort||'Soutenu'}else{let dumb=type.startsWith('dumbbell');$('#fields').innerHTML=(dumb?'<div class="quick-block"><small>BRAS</small><div class="presets arm"><button type="button" data-arm="left" class="'+(type!=='dumbbell_right'?'on':'')+'">GAUCHE</button><button type="button" data-arm="right" class="'+(type==='dumbbell_right'?'on':'')+'">DROIT</button></div></div>':'')+stepper('sets','SÉRIES',d.sets||3,1,1,'SÉRIES')+stepper('reps','RÉPÉTITIONS PAR SÉRIE',d.reps||12,1,1,'RÉP.')+(dumb?stepper('weight','POIDS',d.weight||5,0,.5,'KG'):'')+stepper('rest','REPOS (OPTIONNEL)',d.rest||60,0,15,'S')}updateGain()}
function openPicker() {editId=null;$('#picker').hidden=false;$('#activity').hidden=true;let recent=items.filter(a=>a.user_id===me.id).slice(0,2);$('#recents').innerHTML=recent.length?'<small>RÉCENTS</small>'+recent.map(a=>'<button data-recent="'+a.id+'"><span>'+T[a.type][1]+'</span><b>'+info(a)+'</b>›</button>').join(''):'';if(!$('#modal').open)$('#modal').showModal()}
function openEntry(type,a=null){editId=a?.id||null;$('#picker').hidden=true;$('#activity').hidden=false;$('#type').value=type;$('#modalHeading').textContent=T[type][0];$('#note').value=a?.note||'';$('#date').value=a?.performed_at||new Date().toISOString().slice(0,10);$('#deleteActivity').hidden=!a;buildFields(type,a?.details||{});updateGain()}
function openEdit(id){let a=items.find(x=>x.id===id);if(a?.user_id===me.id){if(!$('#modal').open)$('#modal').showModal();openEntry(a.type,a)}}function num(id){return +($('#'+id)?.textContent||0)}
function updateGain(){let gain=$('#type').value==='walk'?Math.round(+( $('#fields').dataset.distance||4)*10):Math.round(num('sets')*num('reps')/2);$('#xpGain').textContent='+'+gain+' XP'}
$('#add').onclick=openPicker;$$('.close').forEach(b=>b.onclick=()=>$('#modal').close());$('#backPicker').onclick=openPicker;$('#list').onclick=e=>{let b=e.target.closest('[data-edit]');if(b)openEdit(b.dataset.edit)};
$('#picker').onclick=e=>{let p=e.target.closest('[data-pick]');if(p)openEntry(p.dataset.pick);let r=e.target.closest('[data-recent]');if(r)openEdit(r.dataset.recent)};
$('#fields').onclick=e=>{let s=e.target.closest('[data-step]');if(s){let v=$('#'+s.dataset.step),n=Math.max(+v.dataset.min,+v.textContent+ +s.dataset.delta);v.textContent=n;updateGain()}let d=e.target.closest('[data-distance]');if(d){$$('[data-distance]').forEach(x=>x.classList.remove('on'));d.classList.add('on');let n=+d.dataset.distance;$('#customDistance').hidden=n!==0;if(n)$('#fields').dataset.distance=n;updateGain()}let ef=e.target.closest('[data-effort]');if(ef){$$('[data-effort]').forEach(x=>x.classList.remove('on'));ef.classList.add('on');$('#fields').dataset.effort=ef.dataset.effort}let arm=e.target.closest('[data-arm]');if(arm){$$('[data-arm]').forEach(x=>x.classList.remove('on'));arm.classList.add('on');$('#type').value='dumbbell_'+arm.dataset.arm;$('#modalHeading').textContent=T[$('#type').value][0]}};$('#fields').oninput=e=>{if(e.target.id==='distanceInput'){$('#fields').dataset.distance=e.target.value;updateGain()}};
$('#deleteActivity').onclick=async()=>{if(!editId||!confirm('Supprimer définitivement cette activité ?'))return;let {error}=await db.from('activities').delete().eq('id',editId).eq('user_id',me.id);if(!error){$('#modal').close();load()}else $('#activityError').textContent=error.message};
$('#activity').onsubmit=async e=>{e.preventDefault();let type=$('#type').value,d=type==='walk'?{distance:+$('#fields').dataset.distance,duration:num('duration'),effort:$('#fields').dataset.effort}:{sets:num('sets'),reps:num('reps'),rest:num('rest'),weight:$('#weight')?num('weight'):null},payload={type,details:d,note:$('#note').value,performed_at:$('#date').value};let r=editId?await db.from('activities').update(payload).eq('id',editId).eq('user_id',me.id):await db.from('activities').insert({...payload,group_id:team.id,user_id:me.id});$('#activityError').textContent=r.error?.message||'';if(!r.error){$('#modal').close();editId=null;load()}};
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js?v=9').catch(()=>{});db.auth.onAuthStateChange((_e,s)=>setTimeout(()=>boot(s),0));db.auth.getSession().then(x=>boot(x.data.session));

