const db=supabase.createClient('https://etchkccnckeuzsifvgld.supabase.co','sb_publishable_XXJU11HBVpyROr4150rgwg_gEGQjlf1'),$=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);
let me,team,items=[],mode='all',signup=false,editId=null,statType='walk',challenges=[];
const T={walk:['Marche rapide','🚶'],pushup:['Pompes','💪'],abs:['Abdos','⚡'],dumbbell_left:['Haltère · bras gauche','🏋️'],dumbbell_right:['Haltère · bras droit','🏋️'],jumping_jack:['Jumping jacks','⭐'],squat_twist:['Squat avec crunch croisé','🔥'],other:['Autre exercice','✨']};
$('#toggle').onclick=()=>{signup=!signup;$('#authTitle').textContent=signup?'Créer mon compte':'Se connecter';$('#nameBox').hidden=!signup;$('#submit').textContent=signup?'Créer mon compte':'Se connecter';$('#toggle').textContent=signup?'Déjà inscrit ? Se connecter':'Pas encore de compte ? S’inscrire'};
$('#login').onsubmit=async e=>{e.preventDefault();let r=signup?await db.auth.signUp({email:$('#email').value,password:$('#password').value,options:{data:{display_name:$('#name').value||$('#email').value.split('@')[0]}}}):await db.auth.signInWithPassword({email:$('#email').value,password:$('#password').value});$('#authError').textContent=r.error?r.error.message:(signup?'Compte créé. Confirme ton e-mail si demandé.':'')};
$('#logout').onclick=()=>db.auth.signOut();
async function boot(s){$('#auth').hidden=!!s;$('#app').hidden=!s;if(!s)return;let {data,error}=await db.from('profiles').select('*').eq('id',s.user.id).single();if(error){$('#app').innerHTML='<p style="padding:30px">La base doit être initialisée.</p>';return}me=data;$('#who').textContent=me.display_name;loadTeam()}
async function loadTeam(){let {data}=await db.from('group_members').select('group_id,groups(*)').eq('user_id',me.id).maybeSingle();$('#setup').hidden=!!data;$('#dash').hidden=!data;if(!data)return;team=data.groups;$('#code').textContent=team.invite_code;$('#hello').textContent=team.name+', on continue.';load()}
$('#create').onclick=async()=>{let {error}=await db.rpc('create_group',{group_name:$('#groupName').value});$('#groupError').textContent=error?.message||'';if(!error)loadTeam()};$('#join').onclick=async()=>{let {error}=await db.rpc('join_group',{join_code:$('#codeIn').value.toUpperCase()});$('#groupError').textContent=error?.message||'';if(!error)loadTeam()};$('#copy').onclick=()=>navigator.clipboard.writeText(team.invite_code);
async function load(){let {data}=await db.from('activities').select('*,profiles(display_name)').eq('group_id',team.id).order('performed_at',{ascending:false});items=data||[];render();renderLevel();loadChallenges()}
function kind(a){return a.type==='other'&&a.details?.exercise?a.details.exercise:a.type}function volume(a){let d=a.details||{};return kind(a)==='walk'?+(d.distance||0):+(d.sets||0)*+(d.reps||0)}function xpFor(a){return kind(a)==='walk'?Math.round(volume(a)*10):Math.round(volume(a)/2)}function safe(s){let d=document.createElement('div');d.textContent=s;return d.innerHTML}
function info(a){let d=a.details||{};if(kind(a)==='walk')return d.distance+' km · '+d.duration+' min'+(d.effort?' · '+d.effort:'');return d.sets+' séries × '+d.reps+' répétitions'+(d.weight?' · '+d.weight+' kg':'')+(d.rest?' · repos '+d.rest+' s':'')}
function render(){let x=items.filter(a=>mode==='all'||(mode==='mine')===(a.user_id===me.id));$('#list').innerHTML=x.length?x.map(a=>'<div class="entry"><div class="icon">'+T[kind(a)][1]+'</div><div><h3>'+T[kind(a)][0]+' · '+a.profiles.display_name+'</h3><p>'+info(a)+(a.note?' · '+safe(a.note):'')+'</p></div><div class="entryEnd"><time>'+new Date(a.performed_at+'T12:00').toLocaleDateString('fr-FR',{day:'numeric',month:'short'})+'</time>'+(a.user_id===me.id?'<button class="edit" data-edit="'+a.id+'">Modifier</button>':'')+'</div></div>').join(''):'<p class="empty">Aucune activité pour le moment.</p>';let monday=new Date();monday.setHours(0,0,0,0);monday.setDate(monday.getDate()-monday.getDay()+1);$('#week').textContent=items.filter(a=>new Date(a.performed_at+'T12:00')>=monday).length;$('#xp').textContent=items.filter(a=>a.user_id===me.id).reduce((n,a)=>n+xpFor(a),0);renderStats()}
$$('.filters button').forEach(b=>b.onclick=()=>{$$('.filters button').forEach(x=>x.classList.remove('on'));b.classList.add('on');mode=b.dataset.f;render()});
function ownForStat(a){return a.user_id===me.id&&allForStat(a)}function allForStat(a){let k=kind(a);return statType==='dumbbell'?k.startsWith('dumbbell'):k===statType}
function renderStats(){let relevant=items.filter(allForStat),mine=relevant.filter(a=>a.user_id===me.id),partner=relevant.filter(a=>a.user_id!==me.id),days=[];for(let i=6;i>=0;i--){let d=new Date();d.setDate(d.getDate()-i);let iso=d.toISOString().slice(0,10);days.push({d,n:mine.filter(a=>a.performed_at===iso).reduce((s,a)=>s+volume(a),0)})}let max=Math.max(1,...days.map(x=>x.n)),mineTotal=mine.reduce((s,a)=>s+volume(a),0),partnerTotal=partner.reduce((s,a)=>s+volume(a),0),record=Math.max(0,...mine.map(volume)),unit=statType==='walk'?'KM':'RÉP.';$('#statsPanel').innerHTML='<div class="stat-cards"><div><small>MON TOTAL</small><b>'+format(mineTotal)+'</b><span>'+unit+'</span></div><div><small>MON RECORD</small><b>'+format(record)+'</b><span>'+unit+'</span></div></div><div class="chart-title">'+(statType==='walk'?'DISTANCE PAR JOUR':'RÉPÉTITIONS PAR JOUR')+'</div><div class="game-chart">'+days.map(x=>'<div class="game-day"><strong>'+format(x.n)+'</strong><i style="height:'+Math.max(4,x.n/max*120)+'px"></i><span>'+x.d.toLocaleDateString('fr-FR',{weekday:'short'}).slice(0,3)+'</span></div>').join('')+'</div><div class="compare"><small>COMPARAISON · TOTAL</small>'+compareRow('MOI',mineTotal,Math.max(mineTotal,partnerTotal,1),'cyan')+compareRow('PARTENAIRE',partnerTotal,Math.max(mineTotal,partnerTotal,1),'purple')+'</div>'}
function format(n){return Number.isInteger(n)?n:n.toFixed(1)}function compareRow(name,val,max,cls){return '<div class="compare-row"><b>'+name+'</b><i><span class="'+cls+'" style="width:'+val/max*100+'%"></span></i><strong>'+format(val)+'</strong></div>'}
$('#statTabs').onclick=e=>{let b=e.target.closest('[data-stat]');if(!b)return;$$('#statTabs button').forEach(x=>x.classList.remove('on'));b.classList.add('on');statType=b.dataset.stat;renderStats()};
function stepper(id,label,value,min=0,step=1,suffix=''){return '<div class="step-block"><small>'+label+'</small><div class="stepper"><button type="button" data-step="'+id+'" data-delta="-'+step+'">−</button><b id="'+id+'" data-min="'+min+'">'+value+'</b><span>'+suffix+'</span><button type="button" data-step="'+id+'" data-delta="'+step+'">＋</button></div></div>'}
function buildFields(type,d={}){if(type==='walk'){$('#fields').innerHTML='<div class="quick-block"><small>DISTANCE</small><div class="presets"><button type="button" data-distance="2">2 KM</button><button type="button" data-distance="4" class="on">4 KM</button><button type="button" data-distance="5">5 KM</button><button type="button" data-distance="0">LIBRE</button></div><label id="customDistance" hidden>Distance personnalisée (km)<input id="distanceInput" type="number" min=".1" step=".1" value="4"></label></div>'+stepper('duration','DURÉE',d.duration||45,1,5,'MIN')+'<div class="quick-block"><small>EFFORT</small><div class="presets effort"><button type="button" data-effort="Facile">FACILE</button><button type="button" data-effort="Soutenu" class="on">SOUTENU</button><button type="button" data-effort="Intense">INTENSE</button></div></div>';$('#fields').dataset.distance=d.distance||4;$('#fields').dataset.effort=d.effort||'Soutenu'}else{let dumb=type.startsWith('dumbbell');$('#fields').innerHTML=(dumb?'<div class="quick-block"><small>BRAS</small><div class="presets arm"><button type="button" data-arm="left" class="'+(type!=='dumbbell_right'?'on':'')+'">GAUCHE</button><button type="button" data-arm="right" class="'+(type==='dumbbell_right'?'on':'')+'">DROIT</button></div></div>':'')+stepper('sets','SÉRIES',d.sets||3,1,1,'SÉRIES')+stepper('reps','RÉPÉTITIONS PAR SÉRIE',d.reps||12,1,1,'RÉP.')+(dumb?stepper('weight','POIDS',d.weight||5,0,.5,'KG'):'')+stepper('rest','REPOS (OPTIONNEL)',d.rest||60,0,15,'S')}updateGain()}
function openPicker() {editId=null;$('#picker').hidden=false;$('#activity').hidden=true;let recent=items.filter(a=>a.user_id===me.id).slice(0,2);$('#recents').innerHTML=recent.length?'<small>RÉCENTS</small>'+recent.map(a=>'<button data-recent="'+a.id+'"><span>'+T[kind(a)][1]+'</span><b>'+T[kind(a)][0]+' · '+info(a)+'</b>›</button>').join(''):'';if(!$('#modal').open)$('#modal').showModal()}
function openEntry(type,a=null){editId=a?.id||null;$('#picker').hidden=true;$('#activity').hidden=false;$('#type').value=type;$('#modalHeading').textContent=T[type][0];$('#note').value=a?.note||'';$('#date').value=a?.performed_at||new Date().toISOString().slice(0,10);$('#deleteActivity').hidden=!a;buildFields(type,a?.details||{});updateGain()}
function openEdit(id){let a=items.find(x=>x.id===id);if(a?.user_id===me.id){if(!$('#modal').open)$('#modal').showModal();openEntry(kind(a),a)}}function num(id){return +($('#'+id)?.textContent||0)}
function updateGain(){let gain=$('#type').value==='walk'?Math.round(+( $('#fields').dataset.distance||4)*10):Math.round(num('sets')*num('reps')/2);$('#xpGain').textContent='+'+gain+' XP'}
$('#add').onclick=openPicker;$$('.close').forEach(b=>b.onclick=()=>$('#modal').close());$('#backPicker').onclick=openPicker;$('#list').onclick=e=>{let b=e.target.closest('[data-edit]');if(b)openEdit(b.dataset.edit)};
$('#picker').onclick=e=>{let p=e.target.closest('[data-pick]');if(p)openEntry(p.dataset.pick);let r=e.target.closest('[data-recent]');if(r)openEdit(r.dataset.recent)};
$('#fields').onclick=e=>{let s=e.target.closest('[data-step]');if(s){let v=$('#'+s.dataset.step),n=Math.max(+v.dataset.min,+v.textContent+ +s.dataset.delta);v.textContent=n;updateGain()}let d=e.target.closest('[data-distance]');if(d){$$('[data-distance]').forEach(x=>x.classList.remove('on'));d.classList.add('on');let n=+d.dataset.distance;$('#customDistance').hidden=n!==0;if(n)$('#fields').dataset.distance=n;updateGain()}let ef=e.target.closest('[data-effort]');if(ef){$$('[data-effort]').forEach(x=>x.classList.remove('on'));ef.classList.add('on');$('#fields').dataset.effort=ef.dataset.effort}let arm=e.target.closest('[data-arm]');if(arm){$$('[data-arm]').forEach(x=>x.classList.remove('on'));arm.classList.add('on');$('#type').value='dumbbell_'+arm.dataset.arm;$('#modalHeading').textContent=T[$('#type').value][0]}};$('#fields').oninput=e=>{if(e.target.id==='distanceInput'){$('#fields').dataset.distance=e.target.value;updateGain()}};
$('#deleteActivity').onclick=async()=>{if(!editId||!confirm('Supprimer définitivement cette activité ?'))return;$('#deleteActivity').disabled=true;let {data,error}=await db.rpc('delete_my_activity',{activity_id:editId});$('#deleteActivity').disabled=false;if(error){$('#activityError').textContent=error.message;return}if(!data){$('#activityError').textContent='Cette activité est introuvable ou ne t’appartient pas.';return}$('#modal').close();editId=null;load()};
$('#activity').onsubmit=async e=>{e.preventDefault();let selected=$('#type').value,isCustom=['jumping_jack','squat_twist'].includes(selected),d=selected==='walk'?{distance:+$('#fields').dataset.distance,duration:num('duration'),effort:$('#fields').dataset.effort}:{sets:num('sets'),reps:num('reps'),rest:num('rest'),weight:$('#weight')?num('weight'):null};if(isCustom)d.exercise=selected;let payload={type:isCustom?'other':selected,details:d,note:$('#note').value,performed_at:$('#date').value};let r=editId?await db.from('activities').update(payload).eq('id',editId).eq('user_id',me.id):await db.from('activities').insert({...payload,group_id:team.id,user_id:me.id});$('#activityError').textContent=r.error?.message||'';if(!r.error){$('#modal').close();editId=null;load()}};
function totalXpFor(user){return items.filter(a=>a.user_id===user).reduce((n,a)=>n+xpFor(a),0)}
function rankFor(level){return level>=30?'LÉGENDE':level>=20?'ATHLÈTE':level>=10?'COMBATTANT':level>=5?'RÉGULIER':'RECRUE'}
function renderLevel(){let xp=totalXpFor(me.id),level=Math.floor(xp/250)+1,inside=xp%250,rank=rankFor(level);$('#level').textContent=level;$('#bigLevel').textContent=level;$('#rankTitle').textContent=rank;$('#bigRank').textContent=rank;$('#levelXp').textContent=inside;$('#nextLevelXp').textContent=250;$('#levelProgress').style.width=inside/250*100+'%'}
async function loadChallenges(){let {data,error}=await db.from('challenges').select('*').eq('group_id',team.id).order('ends_at',{ascending:true});if(error)return;challenges=data||[];renderChallenges()}
function challengeValue(a,metric){if(metric==='distance')return kind(a)==='walk'?volume(a):0;if(metric==='reps')return kind(a)==='walk'?0:volume(a);return xpFor(a)}
function challengeScores(c){let valid=items.filter(a=>a.performed_at>=c.starts_at&&a.performed_at<=c.ends_at),mine=valid.filter(a=>a.user_id===me.id).reduce((n,a)=>n+challengeValue(a,c.metric),0),other=valid.filter(a=>a.user_id!==me.id).reduce((n,a)=>n+challengeValue(a,c.metric),0);return{mine,other,total:mine+other}}
function renderChallenges(){let active=challenges.filter(c=>c.ends_at>=new Date().toISOString().slice(0,10));$('#challengeList').innerHTML=active.length?active.map(c=>{let s=challengeScores(c),value=c.mode==='coop'?s.total:Math.max(s.mine,s.other),pct=Math.min(100,value/c.target*100),unit=c.metric==='distance'?'KM':c.metric==='xp'?'XP':'RÉP.';return '<article class="challenge-card '+c.mode+'"><div class="challenge-top"><span>'+(c.mode==='coop'?'🤝 COOP':'⚔️ DUEL')+'</span><time>FIN '+new Date(c.ends_at+'T12:00').toLocaleDateString('fr-FR',{day:'numeric',month:'short'})+'</time></div><h3>'+safe(c.name)+'</h3><div class="mission-track"><i style="width:'+pct+'%"></i></div><div class="challenge-score">'+(c.mode==='coop'?'<b>'+format(s.total)+' / '+format(c.target)+' '+unit+'</b>':'<b>MOI '+format(s.mine)+'</b><b>PARTENAIRE '+format(s.other)+'</b>')+'</div>'+(c.reward_text?'<p>🏆 '+safe(c.reward_text)+'</p>':'')+'</article>'}).join(''):'<p class="empty">Aucun défi actif. Lancez votre première mission !</p>';let mineXp=totalXpFor(me.id),others=items.filter(a=>a.user_id!==me.id),otherXp=others.reduce((n,a)=>n+xpFor(a),0),myReps=items.filter(a=>a.user_id===me.id&&kind(a)!=='walk').reduce((n,a)=>n+volume(a),0),otherReps=others.filter(a=>kind(a)!=='walk').reduce((n,a)=>n+volume(a),0);$('#hallGrid').innerHTML='<div><span>🏆</span><small>LEADER XP</small><b>'+(mineXp>=otherXp?me.display_name:'PARTENAIRE')+'</b><em>'+Math.max(mineXp,otherXp)+' XP</em></div><div><span>⚡</span><small>ROI DES RÉP.</small><b>'+(myReps>=otherReps?me.display_name:'PARTENAIRE')+'</b><em>'+format(Math.max(myReps,otherReps))+' RÉP.</em></div>'}
$('#newChallenge').onclick=()=>{let d=new Date();d.setDate(d.getDate()+7);$('#challengeEnd').value=d.toISOString().slice(0,10);$('#challengeModal').showModal()};$('#closeChallenge').onclick=()=>$('#challengeModal').close();
$('#challengeForm').onsubmit=async e=>{e.preventDefault();let payload={group_id:team.id,created_by:me.id,name:$('#challengeName').value.trim(),mode:$('#challengeMode').value,metric:$('#challengeMetric').value,target:+$('#challengeTarget').value,reward_text:$('#challengeReward').value.trim()||null,ends_at:$('#challengeEnd').value};let {error}=await db.from('challenges').insert(payload);$('#challengeError').textContent=error?.message||'';if(!error){$('#challengeModal').close();e.target.reset();loadChallenges()}};
if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js?v=14').catch(()=>{});db.auth.onAuthStateChange((_e,s)=>setTimeout(()=>boot(s),0));db.auth.getSession().then(x=>boot(x.data.session));

